[package]
name = "securestore"
version = "0.99.3"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>", "NeoSmart Technologies"]
edition = "2018"
description = "SecureStore API for creating or decrypting user secrets"
keywords = [ "encryption", "security", "secrets", "cryptography" ]
categories = [ "cryptography", "web-programming", "config" ]
license = "Apache-2.0 OR MIT"
homepage = "http://neosmart.net/blog/2020/securestore-open-secrets-format/"
repository = "https://github.com/neosmart/securestore-rs/tree/master/securestore"

[dependencies]
serde = { version = "1.0.139", features = [ "derive" ] }
serde_json = "1.0.82"

[target.'cfg(not(windows))'.dependencies.openssl]
version = "0.10.41"
features = [ ]

[target.'cfg(windows)'.dependencies.openssl]
version = "0.10.41"
features = [ "vendored" ]

[features]
# default = [ "openssl-vendored" ]
openssl-vendored = [ "openssl/vendored" ]

[dev-dependencies]
tempfile = "3.3.0"
