name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Configure OpenSSL
      if: startsWith(matrix.os, 'windows')
      run: |
        dir "C:\Program Files\OpenSSL"
        dir "C:\Program Files\OpenSSL\lib"
        dir "C:\Program Files\OpenSSL\lib\VC\x64"
        dir "C:\Program Files\OpenSSL\lib\VC\x64\MD"
        echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL\include" >> $env:GITHUB_ENV
        echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL\lib\VC\x64\MD" >> $env:GITHUB_ENV
        echo "C:\Program Files\OpenSSL" >> $env:GITHUB_PATH
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-rustls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build securestore with rustls
      run: cargo build -p securestore --no-default-features --features rustls --verbose
    - name: Test securestore with rustls
      run: cargo test -p securestore --no-default-features --features rustls --verbose
    - name: Build ssclient with rustls
      run: cargo build -p ssclient --no-default-features --features rustls --verbose
